# Generated by Django 4.2 on 2023-04-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Is Banned'),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='', max_length=50, verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.BigIntegerField(default=0, verbose_name='Money'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=20, verbose_name='Password'),
        ),
    ]
