# Generated by Django 4.2 on 2023-04-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('price', models.BigIntegerField(default=0, verbose_name='Price')),
                ('quantity', models.BigIntegerField(default=0, verbose_name='Quantity')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
