# Generated by Django 4.2 on 2023-05-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.BigIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
