# Generated by Django 4.2 on 2023-05-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.BigIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
