# Generated by Django 4.2 on 2023-05-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_delete_user'),
        ('products', '0005_alter_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ManyToManyField(to='users.customer'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order_id',
            field=models.ManyToManyField(to='products.order'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_id',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
