# Generated by Django 4.2 on 2023-05-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_delete_user'),
        ('products', '0007_rename_product_id_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ManyToManyField(to='users.customer'),
        ),
    ]
