# Generated by Django 4.2 on 2023-05-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
