# Generated by Django 4.2 on 2023-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='quantity',
            field=models.BigIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
